# Site settings
baseURL = "https://kasia-portfolio.netlify.app"
languageCode = "en-us"
title = "Portfolio website for Kasia Gasiewska"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Kasia Gasiewska"
  description = "My name is Kasia and this is my portfolio."

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Kasia Gasiewska"
    #subtitle = ""
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Finance"
      url = "blogs/project_finance"

    [[params.navigation.links]]
      name = "Entertainment"
      url = "blogs/project_alcohol"

    [[params.navigation.links]]
      name = "Politics"
      url = "blogs/project_trump"
      
      [[params.navigation.links]]
      name = "Climate"
      url = "blogs/project_climate"
      
      [[params.navigation.links]]
      name = "Society"
      url = "blogs/project_gender"
      
      [[params.navigation.links]]
      name = "Economics"
      url = "blogs/project_GDP"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "Get Started"
      url = "blogs/projects"

    # Button Style 2
    [[params.navigation.button2]]
      name = "Log In"
      url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, my name is Kasia!"
    subtitle = "WELCOME TO MY BEAUTFUL PAGE WHERE YOU CAN SEE ALL THE INTERESTING ANALYSIS I DID! I HOPE YOU LIKE IT!"
  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Economy"
      subtitle = "Exploring stock behaviour and GDP trends"
      image = "pic01.jpg"
      url = "blogs/project_stocks_GDP"

    [[params.tiles.showcase]]
      title = "Entertainment"
      subtitle = "Analysing of IMDB movies and alcohol consumption"
      image = "pic02.jpg"
     url = "blogs/project_alcohol"

    [[params.tiles.showcase]]
      title = "Politics & Society"
      subtitle = "Estimating approval rates for Donald Trump and discussing the gender gap"
      image = "pic03.jpg"
      url = "blogs/project_trump"

    [[params.tiles.showcase]]
      title = "Climate"
      subtitle = "Analysing temperature anomalies throughout the century"
      image = "pic04.jpg"
      url = "blogs/project_climate"

    [[params.tiles.showcase]]
      title = "Society"
      subtitle = "Investigating the relationship between gender, salary and experience"
      image = "pic05.jpg"
      url = "blogs/project_gender"

    [[params.tiles.showcase]]
      title = "Economy"
      subtitle = "Looking into GDP components in 3 countries"
      image = "pic06.jpg"
      url = "blogs/project_GDP"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "A little bit about me"
    subtitle = """My name is Kasia and I come from Poland! I came to the UK 5 years ago to study Philosophy, Politics and Economics. Later I moved to London to work for a bit and now I am doing my Masters at London Business School! Looking forward to showing you my cool projects."""
    buttonText = "Get Started"
    url = "blogs/projects"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "kgasiewska.mfa2021@london.edu"

    [[params.contact.phone]]
    title = "Phone"
    phone = "(0) 7599123456"

    [[params.contact.address]]
    title = "Address"
    street = "Regent's Park"
    city = "London, NW1 4SA"
    country = "United Kingdom"

  # Footer section
  [params.footer]
    enable = true
    copyright = "KasiaG Ltd."

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://www.twitter.com"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com"
      label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/kasia-gasiewska-9a3506133/"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
